### ISSUE TITLE
Nakijk werk.

### ISSUE THREAD

**Issue by gitpeut** [JoryMunsterman/opdracht1en2#1]
Opdracht 1:

Ziet er goed uit, met eigenlijk maar 1 foutje:

Geef het tekst-veld een blauwe rand wanneer hij in focus is
moet zijn:
```
input[type="text"]: {
    background-color: yellowgreen;
}
```

Ik had iets fout wat jij wel goed had gedaan:

Ik had 
```
ul.li {
    color: hsl(110, 29%, 52%);
}
```
Dat moet natuurlijk

```
ul>li {
    color: hsl(110, 29%, 52%);
}
```

zijn.

Opdracht 2:

Daar kwam je op het eind dus niet uit. Kijk de uitwerking nog een na, al zit daar volgens mij een fout in. https://github.com/hogeschoolnovi/frontend-selectors-flexbox-uitwerkingen/blob/uitwerkingen/opdracht-2/index.html

Het belangrijkste is dat er een div om de form heen komt, en die moet je een
id of class geven. In de css van de uitwerking staat een  class four, maar in de bijbehorende 
html staat die niet in de div om de form heen. 

Daarnaast is de truc dat zowel die div als de form flex containers de div omdat er een form in staat, de form omdat er input velden in staan. Maar in de div is de direction row, in de form column. 
Ik had zelf trouwens in de form css align-content staan, wat gewoon fout is, dat moet natuurlijk align-items zijn.

**Comment by JoryMunsterman** [comment]
Merci!
de kleuren zijn veranderd.
